// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxBrzeYj3z7JsmUDaJlxD3kIslxjCex78',
    appId: '1:988983272193:web:9b4656a849bb18373db100',
    messagingSenderId: '988983272193',
    projectId: 'chat-app-32b9a',
    authDomain: 'chat-app-32b9a.firebaseapp.com',
    storageBucket: 'chat-app-32b9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBMIDnqByQRhDvlkLqgr4kOtN5VfaKzYQ',
    appId: '1:988983272193:android:3193ab11696b90a13db100',
    messagingSenderId: '988983272193',
    projectId: 'chat-app-32b9a',
    storageBucket: 'chat-app-32b9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBliy38jmEGrLDKICNFQOn8VZMXVbu6Tgc',
    appId: '1:988983272193:ios:eea419a592c2156a3db100',
    messagingSenderId: '988983272193',
    projectId: 'chat-app-32b9a',
    storageBucket: 'chat-app-32b9a.appspot.com',
    iosClientId: '988983272193-0bucv6vahrj54n4nbvnt6k8b5if7n2e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
